workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      java: 17
      android_signing:
        - resamo_pro_keystore
      groups:
        - base_urls
        - tokens
        - google_credentials
      vars:
        PACKAGE_NAME: "com.dennytech.resamopro"
        GOOGLE_PLAY_TRACK: "alpha"
        JAVA_HOME: "/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home"
        FIREBASE_PROJECT_ID: "resamo-pro"
        ANDROID_BUILD_DIR: "app/build/outputs/apk/release"
        GOOGLE_APPLICATION_CREDENTIALS: "$GOOGLE_APPLICATION_CREDENTIALS"
    triggering:
      events:
        - push
    scripts:
      - name: Install dependencies
        script: ./gradlew build
      - name: Add secrets to local.properties
        script: |
          echo "DEV_URL=${DEV_URL}" >> ./local.properties
          echo "PROD_URL=${PROD_URL}" >> ./local.properties
      - name: Assemble Release APK
        script: ./gradlew assembleRelease
      - name: Install Firebase CLI
        script: npm install -g firebase-tools --force
    artifacts:
      - $ANDROID_BUILD_DIR/app-release.apk
    publishing:
      firebase:
        firebase_service_account: $GOOGLE_APPLICATION_CREDENTIALS
        android:
          app_id: 1:14896196544:android:25d1351bf5dcb2dbc17625
          groups:
            - testers
          artifact_type: 'apk'
      email:
        recipients:
          - olukadeno@gmail.com
        notify:
          success: true
          failure: false